### ISSUE TITLE
wave kakao domain

### ISSUE THREAD

**Issue by seunggabi** [seunggabi/auto-skip#27]
```
2022년 1월 2일 (일) 오전 10:22, 하장훈 <dodanto09@naver.com>님이 작성:
오토스킵을 킨상태로 

 

웨이브 플렛폼 로그인할때 웨이브아이디가 아닌 카카오톡 아이디로 로그인할경우 팝업창이 한개더뜨는데요 

 

그때 아이디를 입력하고 로그인을 누르면 팝업창화면에 아무것도 안뜨고 그대로 끝나버리고 로그인도 안되네요 

 

쿠키를 다지우고 인터넷기록 등등 다지우고 해봤는데도 똑같습니다 오토스킵 확장앱 끄니깐 로그인이되네요 

 

제가 왜 오토스킵이 이상할꺼라고 생각했냐면 계속 잘 쓰던 플렛폼이였는데 오토스킵깔고나서 접속이 안돼서 오토스킵이 문제라고 생각했습니다 

 

또 맞았구요 웨이브 플렛폼을 이용할때마자 오토스킵을 껏다 켯다 해야되는 번거로움이 있어서 이렇게 메일남깁니다

 

개선가능하면 부탁드려요~ ^^ 항상 오토스킵 잘쓰고있습니다 감사합니다
````

**Comment by seunggabi** [comment]
```
Uncaught DOMException: Blocked a frame with origin "https://kauth.kakao.com" from accessing a cross-origin frame.
    at Object.kauth.returnResponse (https://kauth.kakao.com/public/js/common.js:131:22)
    at Object.success (https://kauth.kakao.com/oauth/authorize?client_id=30fc7e17b5c56a0ca1e861643292c203&redirect_uri=kakaojs&response_type=code&state=yf76drvdhlne501u5iegle&proxy=easyXDM_Kakao_tov2u9bf4yo_provider&ka=sdk%2F1.41.0%20os%2Fjavascript%20sdk_type%2Fjavascript%20lang%2Fko-KR%20device%2FMacIntel%20origin%2Fhttps%253A%252F%252Fwww.wavve.com&origin=https%3A%2F%2Fwww.wavve.com:49:23)
    at Reqwest._successHandler (https://kauth.kakao.com/public/js/reqwest.js:293:30)
    at success (https://kauth.kakao.com/public/js/reqwest.js:357:18)
    at XMLHttpRequest.<anonymous> (https://kauth.kakao.com/public/js/reqwest.js:102:33)
```
